config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  mount Sidekiq::Web => '/sidekiq'

  root to: 'pages#home'

  resources :things, only: [:create, :index, :new, :show]
  resources :transactions, only: [:create, :index, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expired_loan.rb
class ExpiredLoan < ApplicationRecord
  def self.refresh
    Scenic
      .database
      .refresh_materialized_view(table_name, concurrently: false, cascade: false)
  end
end

app/models/null_objects/guest_user.rb
module NullObjects
  class GuestUser
    def admin?
      false
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles


  belongs_to :resource,
             :polymorphic => true,
             :optional => true


  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/thing.rb
class Thing < ApplicationRecord
  belongs_to :user
  belongs_to :borrower, class_name: 'User', optional: true

  validates :name, presence: true, length: { maximum: 255 }

  has_one_attached :header_image
  has_many_attached :uploads
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :lender, class_name: 'User'
  belongs_to :borrower, class_name: 'User'
  belongs_to :thing
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  rolify

  has_many :borrowed_things, class_name: 'Thing', foreign_key: 'borrower_id'
  has_many :things, dependent: :destroy
  has_many :transactions_as_borrower, class_name: 'Transaction', foreign_key: 'borrower_id'
  has_many :transactions_as_lender, class_name: 'Transaction', foreign_key: 'lender_id'

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name,  presence: true, length: { maximum: 75 }
  validates :nickname,   length: { maximum: 100 }

  def admin?
    has_role?(:admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def current_user
    @current_user ||= begin
      devise_session_key = session['warden.user.user.key']
      devise_user = User.find(devise_session_key[0][0]) if devise_session_key
      devise_user || NullObjects::GuestUser.new
    end
  end

  def user_signed_in?
    current_user.is_a?(User)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name nickname])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  def index
    things = Thing.all

    render locals: { things: things }
  end

  def show
    thing = Thing.with_attached_uploads.find(params[:id])

    render locals: { thing: thing }
  end

  def new
    thing = current_user.things.new

    render locals: { thing: thing }
  end

  def create
    thing = current_user.things.new(thing_params)

    if thing.save
      redirect_to thing
    else
      render :new, locals: { thing: thing }
    end
  end

  private

  def thing_params
    params.require(:thing).permit(:name, :visible, :description, :header_image, uploads: [])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    transactions = Transaction.all

    render locals: { transactions: transactions }
  end

  def new
    transaction = LendingForm.new(current_user.id)

    render locals: { transaction: transaction }
  end

  def create
    transaction = LendingForm.new(current_user.id, transaction_params)

    if transaction.save
      redirect_to root_path
    else
      render :new, locals: { transaction: transaction }
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(
      :notes,
      :lender_id,
      :borrower_id,
      :thing_id,
      :borrowed_at,
      :return_planned_at
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, 'error')} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/layouts/_footer.html.haml
%footer
  .container
    .footer-bar.col-12
      %p.text-center
        ShareHub 
        %span &copy;
        2018

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to 'ShareHub', root_path, class: 'navbar-brand'
  %button.navbar-toggler{ aria: { controls: "navbarNavDropdown", expanded: "false", label: "Toggle navigation" }, 
												  data: { target: "#navbarNavDropdown", toggle: "collapse" }, 
                          type: "button" }
    %span.navbar-toggler-icon
  #navbarNavDropdown.collapse.navbar-collapse.navbar-right
    %ul.navbar-nav.ml-md-auto
      %li.nav-item.active
        = link_to 'Home', root_path, class: 'nav-link'
      %li.nav-item
        = link_to 'Things', things_path, class: 'nav-link' if current_user.admin?
      %li.nav-item.dropdown
      - if user_signed_in?  
        %a#navbarDropdownMenuLink.nav-link.dropdown-toggle{ aria: { expanded: 'false', haspopup: 'true' },
                                                            data: { toggle: 'dropdown' }, 
                                                            href: '#' }
          = current_user.email 
        .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdownMenuLink"}
          %li= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item' 
          %li= link_to 'Sign out', destroy_user_session_path, class: 'dropdown-item', method: :delete
        = link_to 'New thing', new_thing_path, role: 'button', class: 'btn btn-light'
        = link_to 'Lend something', new_transaction_path, role: 'button', class: 'btn btn-light'
      - else
        %li.nav-item
          = link_to 'Sign in', new_user_session_path, role: 'button', class: 'btn btn-light'
        

app/views/layouts/_messages.html.haml
- flash.each do |msg_type, msg|
  %div{ class: "alert alert-#{msg_type}" }
    %a{ href: "#", data: { dismiss: "alert" }, class: "close" }
      ×
    %ul
      %li= msg

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ShareHub
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
  %body.d-flex.flex-column
    = render 'layouts/header'
    = render 'layouts/messages'
    %main.container
      = yield
    = render 'layouts/footer'

app/views/pages/home.html.haml
%h1 Home

app/views/things/_form.html.haml
= simple_form_for(thing) do |f|
  = f.error_notification
  = f.input :name, label: 'Thing name', error: 'Thing name is mandatory, please specify one'
  = f.input :visible, label: 'Visibility'
  = f.input :description, input_html: { rows: 8 }
  = f.input :header_image, as: :file
  = f.input :uploads, as: :file, input_html: { multiple: true, direct_upload: true }
  = f.error :base
  = f.button :submit, class: 'btn-primary'

app/views/things/_thing.html.haml
%li
  %h3= link_to thing.name, thing
  %p= thing.description

app/views/things/index.html.haml
%h1 All the things

%ul
  = render partial: 'thing', collection: things

app/views/things/new.html.haml
.row.justify-content-center
  .col-sm-6.mt-5.mb-5
    = render partial: 'things/form', locals: { thing: thing }

app/views/things/show.html.haml
%h1= thing.name

= image_tag thing.header_image.variant(resize: '400x400', colorspace: :Gray) if thing.header_image.variable?

%p= thing.description

- thing.uploads.each do |upload|
  - if upload.variable?
    = link_to image_tag(upload.variant(resize: '200x200')), rails_blob_path(upload, disposition: :inline)
  - elsif upload.previewable?
    = link_to image_tag(upload.preview(resize: '200x200')), rails_blob_path(upload, disposition: :inline)
  - else
    = link_to "Download #{upload.filename}", rails_blob_path(upload, disposition: :attachment)

app/views/transactions/_form.html.haml
= simple_form_for(transaction, as: :transaction, url: transactions_path) do |f|
  = f.error_notification
  = f.input :thing_id, collection: transaction.lendable_things 
  = f.input :borrower_id, collection: transaction.borrowers, label_method: :name 
  = f.input :borrowed_at, as: :datetime, html5: true
  = f.input :return_planned_at, as: :datetime, html5: true
  = f.input :notes, input_html: { rows: 8 }
  = f.error :base
  = f.button :submit, class: 'btn-primary'

app/views/transactions/new.html.haml
.row.justify-content-center
  .col-sm-6.mt-5.mb-5
    = render partial: 'transactions/form', locals: { transaction: transaction }